### ISSUE TITLE
Add the buildkite-plugin topic?

### ISSUE THREAD

**Issue by toolmantim** [improbable-eng/perforce-buildkite-plugin#15]
We're working on a new plugins directory (you can preview it here: https://buildkite.com/plugins). Would love this to be added.

It's powered by the [buildkite-plugin](https://github.com/topics/buildkite-plugin) GitHub Topic though. If you wanted to add that to the repo, it should Just Appear™

**Comment by ca-johnson** [comment]
Awesome, thanks Tim. 

I'll definitely add it once this plugin gets a bit more battle-tested.

**Comment by toolmantim** [comment]
https://buildkite.com/plugins 🎉
