### ISSUE TITLE
Support pre-commit testing of shelved changes

### ISSUE THREAD

**Issue by ca-johnson** [improbable-eng/perforce-buildkite-plugin#21]
We need to support a workflow where a user has a changelist on their machine and wants to test it prior to submission.

- [x] Can supply a changelist to a build
- [x] Plugin unshelves this change into the client workspace for each job
- [x] Unshelved changes are reliably cleaned up for following jobs (i.e. restored to match the `#have` list)

Things to consider:
- Downloading large shelves repeatedly - could we cache the shelf in the pipeline upload job?
- Write out a file which lists all the modified files and the mode they were modified in. We can then 'p4 clean' this list of files to ensure consistency with the workspaces `#have` list (or something faster, if it comes to me)

**Comment by arkilus** [comment]
BUILDKITE_PULL_REQUEST seems like the right place to supply this (and/or BUILDKITE_BRANCH - this would allow users to click 'new build' and enter their pending changelist number

**Comment by arkilus** [comment]
Also provide a stronger guarantee that a build is against the same version of a changelist by downloading it once in the first task. Can annotate 'here is the changelist I tested, with modified files: a\nb\nc\n...
