### ISSUE TITLE
p4 print -o (as done in  p4print_unshelve) doesn't "unshelve" changes for files marked for delete

### ISSUE THREAD

**Issue by improbable-mattchurch** [improbable-eng/perforce-buildkite-plugin#247]
p4 print -o (as done in  p4print_unshelve) doesn't "unshelve" changes for files marked for delete. This can result in "unshelving" operations that are not representative of the entire shelf's change.

Repro: 

Mark a file for delete in a shelf and try running the p4 print -o operation to unshelve that changelist version of the file and notice the file does not get removed/cleared 

ex:
">p4 print -o C:\Everest\GameOne\Scavengers\Platforms\PS4\Build\sce_sys\trophy\trophy00.trp //midwinter/main/GameOne/Scavengers/Platforms/PS4/Build/sce_sys/trophy/trophy00.trp@=166298

//midwinter/main/GameOne/Scavengers/Platforms/PS4/Build/sce_sys/trophy/trophy00.trp#5 - delete change 166298 (binary)"

**Comment by LeadTimeNull** [comment]
All files existing locally in the shelve are removed from disk [here](https://github.com/improbable-eng/perforce-buildkite-plugin/blob/490a09d6c9aaf99fec0cc85576a12fd47d45544c/python/perforce.py#L297), before the p4 print cmd is run.

The file(s) should not exist by the point p4 print is called.
Have you experienced any issues that made you suspect there is an issue?

**Comment by improbable-mattchurch** [comment]
Ah nice, I didn't notice that step (and also my first time seeing unlink over remove!). I imagine that will cover all the bases here. I was investigating an unrelated issue and it dawned on me that p4print would be insufficient so I figured I would raise this in case
